estou fazendo um aplicativo de análise de fvs e planilhas esse é o último código preciso que na parte de esquadria se adicione o falta cerâmica ou pasta de gesso

Segue csv atual

 ,,,SERVIÃ‡OS PRECENDENTES DE ESQUADRIA,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
DATA: 15/04/2026,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
LEGENDA,,,,,,,,TOTAL TORRE A,,,,,TOTAL TORRE B,,,,,,TOTAL TORRE C,,,TOTAL TORRE D,,,TOTAL GERAL,,,,,,,,,,,,,,,,,,,,,,,,
S,CONTRAMARCO SUJO,,,,,,,3,,,,,6,,,,,,3,,,5,,,17,,,,,,,,,,,,,,,,,,,,,,,,
C,FALTA CONTRAMARCO,,,,,,,32,,,,,1,,,,,,0,,,10,,,43,,,,,,,,,,,,,,,,,,,,,,,,
P.U,"FALTA P.U/ P.U INCOMPLETO, CONTRAMARCO LIMPO",,,,,,,0,,,,,2,,,,,,4,,,0,,,6,,,,,,,,,,,,,,,,,,,,,,,,
F,FALTA REJUNTE OU FACHADA,,,,,,,1,,,,,48,,,,,,94,,,1,,,144,,,,,,,,,,,,,,,,,,,,,,,,
I,"SERVIÃ‡OS PRECEDENTES CONCLUÃDOS, PRONTO PARA INSTALAÃ‡ÃƒO",,,,,,,24,,,,,20,,,,,,35,,,0,,,79,,,,,,,,,,,,,,,,,,,,,,,,
E,ESQUADRIA INSTALADA,,,,,,,142,,,,,116,,,,,,60,,,194,,,512,,,,,,,,,,,,,,,,,,,,,,,,
CE,FALTA CERÃ‚MICA OU PASTA DE GESSO,,,,,,,0,,,,,2,,,,,,22,,,0,,,24,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
 ,TORRE,PA01             VARANDA  ,JA05                           COZINHA,JA06                                DEPÃ“SITO,JA02                                   BWC SERVIÃ‡O,PA02                                      SUÃTE 01,JA04                                BWC SU01 E 02,JA03                             SUÃTE 02,JA05                           SUÃTE 03,JA03                                            SUÃTE 03,JA04                                               BWC SUÃTE 03,JA02                                               BWC SUÃTE 03,JA01                                        SUÃTE MASTER,JA12                         SUÃTE MASTER,JA04                             BWC SUÃTE MASTER,JA02                         BWC SUÃTE MASTER,JA11                 CAIXA DE ESCADA,,APTO,TORRE,PA01             VARANDA  ,JA10                           COZINHA,JA09                                DEPÃ“SITO,JA02                                   BWC SERVIÃ‡O,PA02                                      SUÃTE 01,JA04                                BWC SU01 E 02,JA03                             SUÃTE 02,JA03                             SUÃTE 03,JA06                                     BWC SUÃTE 03,JA07                                SUÃTE MASTER,JA01                                SUÃTE MASTER,JA04                     BWC SUÃTE MASTER,JA11                 CAIXA DE ESCADA,,,,,,,,,,,,,,,,
1102,A,S,,,E,I,E,E,,E,E,,F,,E,,C,,1102,B,,E,E,,,E,E,E,,,I,E,I,,,,,,,,,,,,,,,,
1101,A,I,E,E,,I,I,E,E,,,E,,E,,E,,,1101,B,,E,F,F,,E,E,E,E,F,,,,,,,,,,,,,,,,,,,
1002,A,,,,E,,E,E,,E,E,,I,,E,,C,,1002,B,,E,E,,,E,E,E,,,I,E,I,,,,,,,,,,,,,,,,
1001,A,I,E,E,,I,E,E,E,,,E,,E,,E,,,1001,B,,E,F,F,,E,E,E,E,F,,,,,,,,,,,,,,,,,,,
902,A,,,,E,,E,E,,E,E,,I,,E,,C,,902,B,,E,E,,,E,E,E,,,I,E,I,,,,,,,,,,,,,,,,
901,A,I,E,E,,I,E,E,E,,,E,,E,,E,,,901,B,F,E,F,F,F,E,E,E,E,I,,,,,,,,,,,,,,,,,,,
802,A,,,,E,,E,E,,E,E,,I,,E,,C,,802,B,,E,E,,,E,E,E,,,I,E,I,,,,,,,,,,,,,,,,
801,A,,E,E,,,E,E,E,,,E,,E,,E,,,801,B,,E,F,F,,CE,E,E,CE,F,,,,,,,,,,,,,,,,,,,
702,A,I,,,E,I,E,E,,E,E,,E,,E,,C,,702,B,S,E,E,,S,E,E,E,,,I,E,I,,,,,,,,,,,,,,,,
701,A,I,E,E,,I,E,E,E,,,E,,E,,E,,,701,B,,E,F,F,,E,E,E,E,F,,,,,TOTAL ESQUADRIAS INSTALADAS,,,,,,,,,,,,,,
602,A,I,,,E,I,E,E,,E,E,,E,,E,,C,,602,B,F,E,E,,F,E,E,E,,,E,E,I,,TORRE,PA01,PA02,JA01,JA02,JA03,JA04,JA05,JA06,JA07,JA09,JA10,JA11,JA12,TOTAL
601,A,I,E,E,,I,E,E,E,,,E,,E,,E,,,601,B,,E,F,F,,E,E,E,E,F,,,,,A,0,0,6,30,30,38,20,8,-,-,-,0,10,142
502,A,,,,E,,E,E,,E,E,,E,,E,,C,,502,B,,E,E,,,E,E,E,,,E,E,I,,B,0,0,5,0,41,29,-,8,0,11,22,0,-,116
501,A,I,E,E,,I,E,E,E,,,E,,E,,E,,,501,B,,E,F,F,,E,E,E,E,F,,,,,C,0,0,-,0,50,10,-,-,-,0,-,0,-,60
402,A,S,,,E,S,I,E,,E,E,,E,,E,,C,,402,B,F,E,E,,F,E,E,E,,,E,E,I,,D,9,9,-,20,63,61,-,-,-,20,-,12,,194
401,A,,E,,,,E,E,E,,,E,,E,,E,,,401,B,,E,F,F,,E,E,E,E,F,,,,,TOTAL,36,18,11,50,184,138,20,16,0,31,22,12,10,512
302,A,,,,E,,E,E,,E,E,,E,,E,,C,,302,B,F,E,E,,F,E,E,E,,,E,E,I,,,,,,,,,,,,,,,,
301,A,,E,,,,E,E,E,,,E,,E,,E,,,301,B,,E,F,F,,E,E,E,P.U,F,,,,,,,,,,,,,,,,,,,
202,A,,,,E,,E,E,,E,E,,E,,E,,C,,202,B,F,E,E,,F,E,E,E,,,E,E,I,,,,,,,,,,,,,,,,
201,A,I,E,E,,I,E,E,E,,,E,,E,,E,,,201,B,F,E,F,F,F,I,F,E,E,F,,,,,,,,,,,,,,,,,,,
102,A,C,,,C,C,C,C,,C,C,,C,,C,,C,,102,B,F,E,E,,F,S,S,E,,,P.U,E,I, ,,,,,,,,,,,,,,,
101,A,C,C,C,,C,C,C,C,,,C,C,C,,C,,,101,B,F,E,F,F,F,S,S,E,I,I,,,,,,,,,,,,,,,,,,,
TÃ‰RREO,,,,,,,,,,,,,,,,,C,,TÃ‰RREO,,,,,,,,,,,,,,C,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,PA01,JA05,JA06,JA02,PA02,JA04,JA03,JA05,JA03,JA04,JA02,JA01,JA12,JA04,JA02,JA11,,,,PA01,JA10,JA09,JA02,PA02,JA04,JA03,JA03,JA06,JA07,JA01,JA04,JA11,,,,,,,,,,,,,,,,
,,0,10,8,10,0,18,20,10,10,10,10,6,10,10,10,0,,,,0,22,11,0,0,18,19,22,8,0,5,11,0,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
APTO,TORRE,PA01             VARANDA  ,COZINHA,JA09                                           DEPÃ“SITO,JA02                                           BWC SERVIÃ‡O,PA02                                     SUÃTE 01,JA04                                         BWC SUÃTE 01 E 02,JA03                                               SUÃTE 02,JA03                                        SUÃTE 03,JA04                                                           BWC SUÃTE 03,JA03                                                    SUÃTE MASTER,JA04                                                           BWC SUÃTE MASTER,JA11                 CAIXA DE ESCADA,,,,,,APTO,TORRE,PA01             VARANDA  ,COZINHA,JA09                                           DEPÃ“SITO,JA02                                           BWC SERVIÃ‡O,PA02                                     SUÃTE 01,JA04                                         BWC SUÃTE 01 E 02,JA03                                               SUÃTE 02,JA04                                                           BWC SUÃTE 03,JA03                                               SUÃTE 03,JA04                                                           BWC SUÃTE MASTER,JA03                           SUÃTE MASTER,JA11                           CAIXA DE ESCADA,,,,,,,,,,,,,,,,,
1102,C,,,F,F,,I,E,E,P.U,E,I,I,,,,,,1102,D,E,,E,E,E,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,
1101,C,F,,F,F,F,I,E,E,P.U,F,CE,,,,,,,1101,D,E,,E,E,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,,
1002,C,,,F,F,,I,E,I,I,E,I,F,,,,,,1002,D,,,E,E,,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,
1001,C,,,F,F,,E,E,E,I,F,CE,,,,,,,1001,D,,,E,E,,E,E,E,E,E,E,,,,,,,,,,,,,,,,,,
902,C,F,,F,F,F,I,E,E,CE,E,I,I,,,,,,902,D,E,,E,E,E,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,
901,C,F,,F,F,F,I,E,CE,I,F,CE,,,,,,,901,D,E,,E,E,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,,
802,C,,,F,F,,I,E,E,F,E,I,I,,,,,,802,D,,,E,E,,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,
801,C,F,,F,F,F,I,E,E,E,F,CE,,,,,,,801,D,,,E,E,,E,E,E,E,E,E,,,,,,,,,,,,,,,,,,
702,C,F,,F,F,F,I,E,E,CE,E,P.U,I,,,,,,702,D,E,,E,E,E,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,
701,C,F,,F,F,F,I,E,E,I,F,CE,,,,,,,701,D,,,E,E,,E,E,E,E,E,E,,,,,,,,,,,,,,,,,,
602,C,F,,F,F,F,I,E,E,CE,E,CE,I,,,,,,602,D,,,E,E,,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,
601,C,F,,F,F,F,E,E,E,I,F,CE,,,,,,,601,D,E,,E,E,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,,
502,C,,,F,F,,F,E,E,P.U,CE,S,I,,,,,,502,D,,,E,E,,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,
501,C,,,F,F,,I,E,E,I,F,CE,,,,,,,501,D,,,E,E,,E,E,E,E,E,E,,,,,,,,,,,,,,,,,,
402,C,F,,F,F,F,E,E,E,CE,E,S,I,,,,,,402,D,E,,E,E,E,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,
401,C,,,F,F,,E,E,E,I,F,CE,,,,,,,401,D,E,,E,E,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,,
302,C,F,,F,F,F,E,E,E,CE,E,CE,CE,,,,,,302,D,,,E,E,,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,
301,C,F,,F,F,F,E,E,E,I,F,CE,,,,,,,301,D,E,,E,E,E,E,E,E,E,E,E,,,,,,,,,,,,,,,,,,
202,C,F,,F,F,F,E,E,E,I,E,F,I,,,,,,202,D,C,,C,C,C,C,C,C,C,C,C,E,,,,,,,,,,,,,,,,,
201,C,F,,F,F,F,E,E,E,S,F,CE,,,,,,,201,D,,,E,E,,E,E,E,E,E,E,,,,,,,,,,,,,,,,,,
102,C,F,,F,F,F,E,E,E,F,E,F,CE,,,,,,102,D,,,E,E,,E,E,F,E,E,E,E,,,,,,,,,,,,,,,,,
101,C,F,,F,F,F,I,I,F,F,F,CE,,,,,,,101,D,S,,S,S,S,E,E,S,E,E,E,,,,,,,,,,,,,,,,,,
TÃ‰RREO,,,,,,,,,,,,,F,,,,,,TÃ‰RREO,,,,,,,,,,,,,E,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,PA01,,JA09,JA02,PA02,JA04,JA03,JA03,JA04,JA03,JA04,JA11,,,,,,,,PA01,,JA09,JA02,PA02,JA04,JA03,JA04,JA03,JA04,JA03,JA11,,,,,,,,,,,,,,,,,
,,0,,0,0,0,9,21,19,1,10,0,0,,,,,,,,9,,20,20,9,21,21,19,21,21,21,12,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
SITUAÃ‡ÃƒO ATUAL TORRES,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,TORRE A,,,,,,,TORRE B,,,,,,,,,,,,TORRE C,,,,,,,TORRE D,,,,,,,,,,,,,,,,,,,,,,
,contramarcos totais ,,,,204,,,contramarcos totais ,,,,,,,,195,,,,contramarcos totais ,,,,218,,,contramarcos totais ,,,,,210,,,,,,,,,,,,,,,,,
,ServiÃ§os precedentes faltantes ,,,,36,,,ServiÃ§os precedentes faltantes ,,,,,,,,57,,,,ServiÃ§os precedentes faltantes ,,,,206,,,ServiÃ§os precedentes faltantes ,,,,,19,,,,,,,,,,,,,,,,,
,esquadrias instaladas,,,,142,,,esquadrias instaladas,,,,,,,,116,,,,esquadrias instaladas,,,,0,,,esquadrias instaladas,,,,,179,,,,,,,,,,,,,,,,,
,ServiÃ§os precedentes concluÃ­dos,,,,24,,,ServiÃ§os precedentes concluÃ­dos,,,,,,,,20,,,,ServiÃ§os precedentes concluÃ­dos,,,,0,,,ServiÃ§os precedentes concluÃ­dos,,,,,0,,,,,,,,,,,,,,,,,
,Percentual de esquadrias instaladas ,,,,"69,61%",,,Percentual de esquadrias instaladas ,,,,,,,,"59,49%",,,,Percentual de esquadrias instaladas ,,,,"0,00%",,,Percentual de esquadrias instaladas ,,,,,"85,24%",,,,,,,,,,,,,,,,,
